### PR TITLE
Main and UseCaseFactories

### PR DESCRIPTION
**Pull request by arvintoqm**
I created all of the UseCaseFactories but the game one since the gameView has not been finished yet. I also edited a lot of the files since there was issues with them that would not allow the program to run properly. Everything works together execpt for the gameView. Need to add gameUseCaseFactory which Jenny has done, I have some code in main that creates one for now just for testing which needs to be deleted onces the GameUseCaseFactory has also been merged into it and added.

### CODE REVIEW

**Review by jenny-moore — COMMENTED** [review]
Mostly looks good, is there a reason you deleted the case for the choose view where the user doesn't select anything?

**Comment by arvintoqm** [comment]
Oh sorry I did not realize that is what that was doing I just kept on getting an empty error box so I thought it was not doing anything, we can revert it back to the original way.

**Review by jenny-moore — COMMENTED** [review]
The view factories look good, we might have to delete the game one once we merge my code in. Also, I'm pretty sure I know what's wrong with the choose error message implementation, so it'd be nice if you could revert those changes before merging this branch in. I also resolved the merge conflicts so once that's done it should be good.

**Review by jenny-moore — APPROVED** [review]
Thanks! Looks good to me.

**Pull request merged**
